version: '3'
services:
  meilisearch:
    image: 'getmeili/meilisearch:v1.9'
    ports:
      - '7700:7700'
    volumes:
      - 'sdk-meilisearch:/data.ms'
    networks:
      - sdk-meilisearch
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health" ]
      retries: 3
      timeout: 5s
networks:
  sdk-meilisearch:
    driver: bridge
volumes:
  sdk-meilisearch:
    driver: local
