name: Publish Jitpack

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04

    steps:
      - uses: badasintended/autojitpack@v1
        with:
          version: ${{ github.event.release.tag_name }}
